#!/bin/csh -f

set TOUCH = ORIG
if ( ! -e configure.hwrf ) then
	touch configure.hwrf
	set TOUCH = TOUCH
endif

set nonomatch

(make -i clean )



if ( "$1" == '-a' ) then
	( make -i cleanall >& /dev/null )
	if ( -e configure.hwrf ) then
		/bin/cp configure.hwrf configure.hwrf.backup
		/bin/rm -f configure.hwrf
	endif
#	The nuclear option
	find . -name \*.exe -exec \rm {} \; 
	find . -name \*.o -exec \rm {} \; 
	find . -name \*.a -exec \rm {} \; 
	find . -name \*.mod -exec \rm {} \; 
endif

if ( ( $TOUCH == TOUCH ) && ( -e configure.hwrf ) ) then
	/bin/rm -f configure.hwrf
endif
