#!/bin/csh -f

set TOUCH = ORIG
if ( ! -e configure.cpl ) then
	touch configure.cpl
	set TOUCH = TOUCH
endif

set nonomatch

(make -i clean )



if ( "$1" == '-a' ) then
	( make -i cleanall >& /dev/null )
	if ( -e configure.cpl ) then
		/bin/cp configure.cpl configure.cpl.backup
		/bin/rm -f configure.cpl
	endif
#	The nuclear option
	find . -name \*.exe -exec \rm {} \; 
	find . -name \*.o -exec \rm {} \; 
	find . -name \*.a -exec \rm {} \; 
	find . -name \*.mod -exec \rm {} \; 
endif

if ( ( $TOUCH == TOUCH ) && ( -e configure.cpl ) ) then
	/bin/rm -f configure.cpl
endif
