      PROGRAM READ_MULTI_AUX_WRITE_ONE
!
!.. READ ALL HOURLY AUXILIRARY HWRF OUPUT FILES AND WRITE TO ONE FILE FOR WAVE MODEL
!
      REAL, ALLOCATABLE :: U10(:,:),V10(:,:)
      REAL, ALLOCATABLE :: LAT(:,:),LON(:,:),ACPREC(:,:)
      INTEGER IM,JM,IC,IDUM           !IC: TOTAL NUBER OF AUX FILES
      CHARACTER IND*180,OUTF*180,INF1*1,INF2*2,INF3*3
!
      READ(5,*) IC
      IF(IC.LE.0) THEN
      PRINT *,'THE NUMBER OF AUX FILES ARE LESS THEN ZERO'
      PRINT *,'QUITTING'
      STOP
      ENDIF
!
10    FORMAT(A180)
      READ(5,10) IND
      READ(5,10) OUTF
!
!.. READ THE FIRST FILE TO GET THE DIMENSIONS OF VARIABLES
!
      OPEN(1,FILE=TRIM(IND)//'1',STATUS='OLD',FORM='UNFORMATTED')
      READ(1) IM,JM
      PRINT *,'I & J DIMENSION ',IM,JM
      ALLOCATE (U10(IM,JM))
      ALLOCATE (V10(IM,JM))
      ALLOCATE (LAT(IM,JM))
      ALLOCATE (LON(IM,JM))
      ALLOCATE (ACPREC(IM,JM))
      CLOSE(1)
!
!.. OPEN OUTPUT FILE
!
      OPEN(500,FILE=TRIM(OUTF),STATUS='UNKNOWN',FORM='UNFORMATTED')
!
!.. READ AUX FILES SEQUENTLY
!
      DO IT = 1,IC
      PRINT *,'IT ',IT
!
      IF(IT.LE.9) THEN
      WRITE(INF1,'(I1)') IT
      PRINT *,'INPUT FILE WITH DIR  ',TRIM(IND)//TRIM(INF1)
      OPEN(IT+10,FILE=TRIM(IND)//TRIM(INF1),STATUS='OLD',FORM='UNFORMATTED')
!
      ELSEIF(IT.GE.10.AND.IT.LE.99) THEN
      WRITE(INF2,'(I2)') IT
      PRINT *,'INPUT FILE WITH DIR  ',TRIM(IND)//TRIM(INF2)
      OPEN(IT+10,FILE=TRIM(IND)//TRIM(INF2),STATUS='OLD',FORM='UNFORMATTED')
!
      ELSEIF(IT.GE.100) THEN
      WRITE(INF3,'(I3)') IT
      PRINT *,'INPUT FILE WITH DIR  ',TRIM(IND)//TRIM(INF3)
      OPEN(IT+10,FILE=TRIM(IND)//TRIM(INF3),STATUS='OLD',FORM='UNFORMATTED')
      ENDIF
!
      READ(IT+10) IM,JM
      PRINT *,'I J ',IM,JM
      READ(IT+10) U10
      PRINT *,'SAMPLE U10 AT 10 10  ',U10(10,10)
      READ(IT+10) V10
      PRINT *,'SAMPLE V10 AT 10 10  ',V10(10,10)
      READ(IT+10) LAT
      PRINT *,'SAMPLE LAT AT 10 10  ',LAT(10,10)
      READ(IT+10) LON
      PRINT *,'SAMPLE LON AT 10 10  ',LON(10,10)
      READ(IT+10) ACPREC
      PRINT *,'SAMPLE ACPREC AT 10 10  ',ACPREC(10,10)
!
      IF(IT.EQ.1) WRITE(500) IM,JM
      WRITE(500) U10
      WRITE(500) V10
      WRITE(500) LAT
      WRITE(500) LON
      WRITE(500) ACPREC
      ENDDO
!
      DEALLOCATE (U10)
      DEALLOCATE (V10)
      DEALLOCATE (LAT)
      DEALLOCATE (LON)
!
      STOP
      END
