      MODULE SP_GRID_MODULE

      IMPLICIT NONE

      integer,parameter::real_32=selected_real_kind(6,30)

      INTEGER :: SPNLEVS

      REAL,ALLOCATABLE:: PGRID(:,:,:)
      REAL(REAL_32),ALLOCATABLE,DIMENSION(:,:,:)::TGRID
      REAL(REAL_32),ALLOCATABLE,DIMENSION(:,:,:)::UGRID
      REAL(REAL_32),ALLOCATABLE,DIMENSION(:,:,:)::VGRID
      REAL(REAL_32),ALLOCATABLE,DIMENSION(:,:,:)::QGRID
      REAL(REAL_32),ALLOCATABLE,DIMENSION(:,:,:)::CWMGRID
      REAL(REAL_32),ALLOCATABLE,DIMENSION(:,:,:)::PRESGRID
      REAL(REAL_32),ALLOCATABLE,DIMENSION(:,:,:)::PINTGRID

      END MODULE SP_GRID_MODULE
